config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  resources :carts
  resources :users

  resources :cart_items
  
  root to: 'pages#home'

  get 'shop', to: 'pages#shop'
  get 'products/:id/view', to: 'pages#view_product'

  post '/cart/add_item', to: 'carts#add_item'
  
  get '/cart', to: 'carts#show_cart'

  put '/cart/:id/update_status', to: 'carts#update_status'

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  enum status: { active: "active", archived: "archived" }

  def total_sale
    cart_items = CartItem.where(cart_id: self.id)
    total_sale = 0
    cart_items.each do |cart_item|
      total_sale += cart_item.total
    end
    total_sale
  end

  def total_products
    cart_items = CartItem.where(cart_id: self.id)
    total_items = 0
    cart_items.each do |cart_item|
      total_items += cart_item.quantity
    end
    total_items
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :add_item
  before_action :set_cart, only: %i[ show destroy ]


  def index
    @active_carts = Cart.where(status: :active)
    unless current_user.admin?
      @active_carts = @active_carts.where(status: :active, user_id: current_user.id)
    end
    @archived_carts = Cart.where(status: :archived)
    unless current_user.admin?
      @archived_carts = @archived_carts.where(status: :archived, user_id: current_user.id)
    end
  end

  def show
  end

  def update_status
    cart = Cart.find(params[:id])
    cart.update(status: :archived)
    redirect_to "/carts", notice: "Carrito guardado correctamente"
  end
  
  def show_cart
    @products = Array.new
    if session[:product_ids].present?
      @product_ids = session[:product_ids].sort
      @product_ids= @product_ids.group_by{ |x| x }.values
      @product_ids.each do |product_id|
        @products << [Product.find(product_id[0]), product_id.length ]
      end
    end
  end

  def delete
      
  end
  
  def add_item
    qty =  params[:qty].to_i
    product_id = params[:product_id]
    carts = Cart.where(user_id: current_user.id, status: :active)
    if carts.present?
      cart = carts.last
    else
      cart = Cart.create!(user_id: current_user.id)
    end

    cart_item = CartItem.find_or_create_by(product_id: product_id, cart_id: cart.id)
    cart_item.quantity += qty
    cart_item.save

    respond_to do |f|
        f.json { render json: { total_products: cart.total_products }, status: :ok }
    end
  end

  def update
      
  end

  def destroy
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Carrito eliminado correctamente" }
      format.json { head :no_content }
    end
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_card.html.erb
<div class="cart-card">
  <div class="d-flex space-between align-center">
    <div class="content">
      <% if current_user.admin? %>
      <p>Cliente: <b><%= cart.user.label %></b></p>
      <p>Fecha de creación: <b><%= cart.created_at.strftime("%d - %m - %Y") %></b></p>
        
      <% end %>
      <p>Folio: <b><%= cart.id %></b></p>
      <p>Total de prodcutos: <b><%= cart.total_products %></b></p>
      <p>Monto total: <b><%= cart.total_sale %></b></p>
    </div>
    <div class="actions">
      <p>
        <%= link_to cart, class: 'px-5 btn-action' do %> <i class="fa-solid fa-eye"></i> <% end %>
        <%= link_to cart, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'px-5 btn-action' do %> <i class="fa-solid fa-trash"></i> <% end %>
        <% if cart.active? %>
          <%= link_to "/cart/#{ cart.id }/update_status", method: :put, data: { confirm: '¿Estás seguro?' }, class: 'px-5 btn-action' do %> <i class="fa-regular fa-floppy-disk"></i> <% end %>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/carts/index.html.erb
<div class="container">
  <%= render partial: "layouts/breadcrumb", locals: { previus_message: "Volver al inicio", previus: root_path, current: "Lista de compras" } %>
</div>

<div class="container">
  <h2>Compras</h2>  
  <div class="cart-index-grid">
    <% @active_carts.each do |cart| %>
      <%= render partial: "cart_card", locals: { cart: cart }%>
    <% end %>
  </div>
  <div class="container">
    <hr>
  </div>
  <div class="container">
    <h2>Compras archivadas</h2>
    <div class="cart-index-grid">
      <% @archived_carts.each do |cart| %>
        <%= render partial: "cart_card", locals: { cart: cart }%>
      <% end %>
    </div>
  </div>
  <br>
  <br>
</div>

app/views/carts/show.html.erb
<div class="container">
  <%= render partial: "layouts/breadcrumb", locals: { previus_message: "Volver a lista", previus: carts_path, current: "Carrito" } %>
</div>
<div class="container">
<h3>Mi carrito</h3>
<% if @cart.cart_items %>
  <% @cart.cart_items.each do |cart_item| %>
    <div class="cart-item">
        <div>
          <div class="product-info">
            <a href="/products/<%= cart_item.product.id %>" class="link-basic">
              <h3><%= cart_item.product.title %></h3>
            </a>
            <div class="item-description">
              <p> Description: <%= cart_item.product.description %></p>
              <p> Cantidad:<strong> <%= cart_item.quantity %></strong></p>
              <p> Total:<strong> <%= cart_item.total %></strong></p>
            </div>

            <div class="actions"><%= link_to cart_item, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'px-5 btn btn-danger', style: "padding: 5px 10px" do %> Eliminar </i> <% end %></div>
          </div>
        </div>
    </div>
  <% end %>
<% else %>
  <h4>Comience agregando articulos a su carrito</h4>
  <a href="/shop" class="link-basic">Ver Todo</a>
<% end %>

</div>

app/views/carts/show_cart.html.erb
<div class="container">
  <%= render partial: "layouts/breadcrumb", locals: { previus_message: "Volver a lista", previus: "/shop", current: "Carrito" } %>
</div>
<div class="container">
<h3>Mi carrito</h3>
<% if @products.any? %>
  <% @products.each do |item| %>
    <div class="cart-item">
        <div class="d-flex space-between align-center">
          <div class="product-info">
            <a href="/products/<%= item[0].id %>" class="link-basic">
              <h3><%= item[0].title %></h3>
            </a>
            <p> Description: <%= item[0].description %></p>
            <p> Cantidad:<strong> <%= item[1] %></strong></p>
          </div>
          <div class="cart-item-actions">
            <%= link_to item[0], method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'px-5 btn-action' do %> <i class="fa-solid fa-trash"></i> <% end %>
          </div>
        </div>
    </div>
  <% end %>
<% else %>
  <h4>Comience agregando articulos a su carrito</h4>
  <a href="/shop" class="link-basic">Ver Todo</a>
<% end %>

</div>